version: '3'
networks:
  web:
services:
  web:
    image: nginx:1.13
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web

  PLN:
    image: python:3.7.2
    volumes: 
      - ./PLN:/PLN
      - ./web:/usr/share/nginx/html
    environment:
      - PYTHONUNBUFFERED=0
    working_dir: /PLN
    command: bash ./PLN.sh
    networks: 
      - web
