version: '3'
networks:
  web:
services:
  web:
    image: nginx:1.13
    volumes:
      #Site
      - ./web:/usr/share/nginx/html
      # Proxy Reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - web
    #depends_on: 
    #  - app
  PLN:
    image: python:3.7.2
    volumes: 
      - ./PLN:/PLN
    working_dir: /PLN
    command: bash ./PLN.sh
    networks: 
      - web
