FROM python:3.72.
LABEL mantainer "Jonathan Camargo <jonathanpcamargo@gmail.com>"

ENV PYTHONUNBUFFERED 1
RUN pip install nltk==3.5 && sklearn==0.0 && pandas==1.0.4

ENTRYPOINT ["/usr/local/bin/python"]